name: WorldWarp
main: Raz.WorldWarp.WorldWarp
version: 3.3
commands:
  wcreate:
    description: Creates a new world
    usage: /<command> [name] [environmate] <seed>
  wlist:
    description: List worlds
    usage: /<command>    
  wflag:
    description: Set PVP / Difficulty in world.
    usage: /<command> [name] -flags
  wwarp:
    description: Warp to worlds
    usage: /<command> [name]  
  wdelete:
    description: Delete worlds
    usage: /<command> [name] -flags     
  wimport:
    description: Import worlds
    usage: /<command> [name]       
  wback:
    description: Go back to last known position
    usage: /<command>
permissions:
    WorldWarp.wcreate:
        description: Allows you to create a world
        default: false
    WorldWarp.wflag:
        description: Allows you to flag a world
        default: false
    WorldWarp.wdelete:
        description: Allows you to delete a world
        default: false
    WorldWarp.wwarp:
        description: Allows you to warp to a world
        default: false
    WorldWarp.wlist:
        description: Allows you to list worlds
        default: false
    WorldWarp.wimport:
        description: Allows you to import worlds
        default: false        
    WorldWarp.wback:
        description: Allows you to go back
        default: false     